# Generated by Django 5.1.4 on 2024-12-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('sugar_level', models.FloatField()),
                ('bmi', models.FloatField()),
                ('pulse_rate', models.FloatField()),
                ('hemoglobin_level', models.FloatField()),
                ('uric_acid_level', models.FloatField()),
                ('cholesterol_level', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='HealthImage',
        ),
    ]
